### ISSUE TITLE
Reading Data with Usage Policy

### ISSUE THREAD

**Issue by Jonathan-Denzel** [sem-con/sc-base#10]
When will a method for requesting data with a usage policy in a json body be implemented? So far  the API only provides write access with a usage policy check.

**Comment by fabianekc** [comment]
Hi Jonathan, this is already available! 
Any `GET /api/data` returns also the Usage Policy.

**Comment by fabianekc** [comment]
have a look at this Tutorial for an example: https://github.com/sem-con/Tutorials/blob/master/1_Usage/README.md

**Comment by Jonathan-Denzel** [comment]
I actually meant to access the data only with a matching usage policy. But I misunderstood the purpose of the semantic container. The way I understand the purpose of the container is that once data is uploaded in a container further restriction of data access with usage policies are not intended. I do not want to read the usage policy, I want to be given access to the data because I have a matching usage policy.

**Comment by fabianekc** [comment]
Usage Policies are only checked/verified when you write data into a Semantic Container. You always need both parties:
- a data subject providing data and a usage policy (originating container)
- a data controller receiving data and stating it's own usage policy (destination container)
Upon receiving data from the data subject the Semantic Container of the data controller uses the configured reasoner to check if the usage policies are compatible; if and only if this is the case the data controller accepts the data and stores it in the container
There are different reasoners available. Here is an example of interpreting the results of the reasoner to only accept subsets of a data category: https://github.com/sem-con/sc-diabetes/tree/master/dataflows/Data_Donation

**Comment by Jonathan-Denzel** [comment]
Thank you for your clarification.
